# Generated by Django 3.1.7 on 2021-04-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.promocao'),
            preserve_default=False,
        ),
    ]
