# Generated by Django 3.1.7 on 2021-04-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210406_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens_em_estoque', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produto')),
            ],
        ),
    ]
