# Generated by Django 3.1.7 on 2021-04-06 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210406_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estoque',
            new_name='GerenciamentoEstoque',
        ),
    ]
