# Generated by Django 3.1.7 on 2021-04-09 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210409_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.promocao'),
        ),
    ]
